port 1194
proto tcp
dev tun

topology subnet
server 10.8.0.0 255.255.255.0
client-config-dir /etc/openvpn/ccd

ca /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key /etc/openvpn/server.key
dh /etc/openvpn/dh.pem

auth SHA1
cipher AES-128-CBC
data-ciphers AES-128-CBC
data-ciphers-fallback AES-128-CBC

auth-user-pass-verify /etc/openvpn/checkpsw.sh via-file
script-security 3

username-as-common-name

keepalive 10 60
persist-key
persist-tun

explicit-exit-notify 0
duplicate-cn

verify-client-cert none

tun-mtu 1500
mssfix 1400

verb 3
